### ISSUE TITLE
💰 USD 200 BOUNTY: Create example showing in-browser file encryption with private key

### ISSUE THREAD

**Issue by fulldecent** [bitchan/eccrypto#72]
I am committing a USD 200 bounty for help that solves this issue.

# Work plan

- [x] Fix #71.
- [x] Fix #48.
- [x] Provide a single page HTML file that proves that #71 and #48 are fixed.

# Details

- Offer is good for 14 days (ends 2020-12-08 at Noon New York)
- I will pay you using PayPal
- Offer not valid for people that are legally disallowed to receive payments from USA
- Anybody else that would like to commit money can increase this number

**Comment by xpepermint** [comment]
Ref: https://github.com/pedrouid/eccrypto-js/

**Comment by xpepermint** [comment]
The correct title should be "Create example showing in-browser file encryption with public key and decryption with private key".

**Comment by ChaituVR** [comment]
@xpepermint @fulldecent so the problem here is with 
https://github.com/bitchan/eccrypto/blob/ee2518544ca36849e4618907dea3c8e3a34a00b0/browser.js#L21
as mentioned in https://github.com/bitchan/eccrypto/issues/48#issuecomment-565681777

If you are not using browserify we cant have a `Buffer`, so the quick fix for you here is to use https://github.com/feross/buffer
instead of `Uint8Array`

and for CDN we can use unpkg's eccrypto-js which supports file integrity 
https://unpkg.com/eccrypto-js@5.3.0/dist/umd/index.min.js

and here is the codepen for working version
https://codepen.io/ChaituVR/pen/GRjKEMZ

below is HTML that is working
```html
<head>
<title>LET's ENCRYPT</title>
<script src="https://bundle.run/buffer@6.0.3"></script>
<script>
    window.Buffer = buffer.Buffer
</script>
<script src="https://unpkg.com/eccrypto-js@5.3.0/dist/umd/index.min.js"></script>
<script>
    function hexToString(hexString) {
        return new Buffer.from(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
    }
    (async function(){
      let eccryptoJS = window.eccryptoJS;
      let privateKey = hexToString("8da4ef21b864d2cc526dbdb2a120bd2874c36c9d0a1fb7f8c63d7f7a8b41de8f");
      let publicKey = eccryptoJS.getPublic(privateKey);
      keyPair = { publicKey, privateKey};
    
      const str = 'test message to encrypt';
      const msg = eccryptoJS.utf8ToBuffer(str);
    
      const encrypted = await eccryptoJS.encrypt(keyPair.publicKey, msg);
      console.log('encrypted:', encrypted);
      const decrypted = await eccryptoJS.decrypt(keyPair.privateKey, encrypted);
      console.log('decrypted:', decrypted);
      let decryptedstring = new TextDecoder("utf-8").decode(decrypted);
      console.log(decryptedstring)
    })()</script>
</head>
<body>
  OPEN CONSOLE
</body>
```


PS: https://bundle.run/buffer@6.0.3 this CDN is recommended in https://github.com/feross/buffer

**Comment by fulldecent** [comment]
Thank you for the fast reply! @xpepermint please confirm works.

**Comment by xpepermint** [comment]
Confirmed!

**Comment by fulldecent** [comment]
@ChaituVR thank you for all your help. Please let me know your PayPal email address, or you can send it to me at GitHub.com@phor.net.

**Comment by fulldecent** [comment]
Thank you for your help. Bounty paid by PayPal. Closing issue.

**Comment by fulldecent** [comment]
@ChaituVR please confirm here receipt of payment.

**Comment by ChaituVR** [comment]
Received it :thumbsup: thank you so much
